"""
Runtime artifact generators.
These prove execution awareness — our output isn't just JSON,
it directly generates working code files.
"""

from schemas.models import DBSchema, APISchema, AuthSchema, IntentSchema, RuntimeArtifacts

# ── Type mappings ─────────────────────────────────────────────────────────────

DB_TO_PRISMA = {
    "uuid":      "String  @default(uuid())",
    "varchar":   "String",
    "text":      "String",
    "integer":   "Int",
    "bigint":    "BigInt",
    "float":     "Float",
    "boolean":   "Boolean",
    "timestamp": "DateTime",
    "json":      "Json",
}

DB_TO_ZOD = {
    "uuid":      "z.string().uuid()",
    "varchar":   "z.string()",
    "text":      "z.string()",
    "integer":   "z.number().int()",
    "bigint":    "z.bigint()",
    "float":     "z.number()",
    "boolean":   "z.boolean()",
    "timestamp": "z.string().datetime()",
    "json":      "z.record(z.unknown())",
}

METHOD_TO_HTTP = {
    "GET":    "get",
    "POST":   "post",
    "PUT":    "put",
    "PATCH":  "patch",
    "DELETE": "delete",
}


def generate_prisma(db: DBSchema, app_name: str) -> str:
    """Generate a complete Prisma schema from DBSchema."""
    lines = [
        "// Generated by Solum AI",
        f"// App: {app_name}",
        "",
        "generator client {",
        '  provider = "prisma-client-js"',
        "}",
        "",
        "datasource db {",
        '  provider = "postgresql"',
        '  url      = env("DATABASE_URL")',
        "}",
        "",
    ]

    for table in db.tables:
        model_name = "".join(w.capitalize() for w in table.name.split("_"))
        lines.append(f"model {model_name} {{")

        for col in table.columns:
            prisma_type = DB_TO_PRISMA.get(col.type, "String")
            base_type = prisma_type.split("  ")[0]
            attr_part = "  ".join(prisma_type.split("  ")[1:])

            modifiers = []
            if col.primary_key:
                modifiers.append("@id")
            if col.unique:
                modifiers.append("@unique")
            if col.default == "now()":
                modifiers.append("@default(now())")
            elif col.default and col.default != "null":
                modifiers.append(f'@default("{col.default}")')

            nullable = "?" if col.nullable and not col.primary_key else ""
            mod_str = " ".join(modifiers)
            lines.append(
                f"  {col.name:<20} {base_type}{nullable}  {attr_part} {mod_str}".rstrip()
            )

        for col in table.columns:
            if col.foreign_key:
                ref_table = col.foreign_key.split(".")[0]
                ref_model = "".join(w.capitalize() for w in ref_table.split("_"))
                rel_field = ref_table.rstrip("s")
                lines.append(
                    f"  {rel_field:<20} {ref_model}  "
                    f"@relation(fields: [{col.name}], references: [id])"
                )

        lines.append("")
        lines.append(f'  @@map("{table.name}")')
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def generate_express_routes(api: APISchema, auth: AuthSchema, app_name: str) -> str:
    """Generate Express.js route stubs with Zod validation and JWT middleware."""
    lines = [
        "// Generated by Solum AI",
        f"// App: {app_name}",
        "// Install: npm install express zod jsonwebtoken",
        "",
        "const express = require('express');",
        "const { z } = require('zod');",
        "const jwt = require('jsonwebtoken');",
        "",
        "// ─── Auth Middleware ──────────────────────────────────────────────",
        "function requireAuth(roles = []) {",
        "  return (req, res, next) => {",
        "    const token = req.headers.authorization?.split(' ')[1];",
        "    if (!token) return res.status(401).json({ error: 'Unauthorized' });",
        "    try {",
        "      const payload = jwt.verify(token, process.env.JWT_SECRET);",
        "      if (roles.length && !roles.includes(payload.role))",
        "        return res.status(403).json({ error: 'Forbidden' });",
        "      req.user = payload;",
        "      next();",
        "    } catch { res.status(401).json({ error: 'Invalid token' }); }",
        "  };",
        "}",
        "",
        "// ─── Routes ──────────────────────────────────────────────────────",
    ]

    groups: dict[str, list] = {}
    for ep in api.endpoints:
        parts = ep.path.strip("/").split("/")
        resource = parts[1] if len(parts) > 1 else parts[0]
        groups.setdefault(resource, []).append(ep)

    for resource, endpoints in groups.items():
        lines.append(f"\n// {resource.upper()}")
        lines.append(f"const {resource}Router = express.Router();")
        lines.append("")

        for ep in endpoints:
            if ep.request_body and ep.request_body.fields:
                zod_fields = ", ".join(
                    f"\n    {k}: {DB_TO_ZOD.get(v, 'z.string()')}"
                    for k, v in ep.request_body.fields.items()
                )
                lines.append(f"const {ep.id}Schema = z.object({{{zod_fields}\n}});")
                lines.append("")

            path = ep.path.replace(api.base_path, "")
            resource_path = "/" + "/".join(path.strip("/").split("/")[1:])
            if not resource_path or resource_path == "/":
                resource_path = "/"

            method = METHOD_TO_HTTP.get(ep.method, "get")
            if ep.requires_auth:
                roles_str = ", ".join(f'"{r}"' for r in ep.roles)
                auth_mw = f"requireAuth([{roles_str}]), "
            else:
                auth_mw = ""

            lines.append(f"// {ep.name} — {ep.description}")
            lines.append(
                f"{resource}Router.{method}('{resource_path}', {auth_mw}async (req, res) => {{"
            )

            if ep.request_body and ep.request_body.fields:
                lines.append(f"  const parsed = {ep.id}Schema.safeParse(req.body);")
                lines.append(
                    "  if (!parsed.success) "
                    "return res.status(400).json({ error: parsed.error });"
                )

            lines.append(f"  // TODO: implement {ep.name}")
            lines.append(f"  // DB table: {ep.db_table}")
            lines.append("  res.json({ message: 'Not implemented yet' });")
            lines.append("});")
            lines.append("")

    lines.append("\n// ─── App Assembly ────────────────────────────────────────────────")
    lines.append("const app = express();")
    lines.append("app.use(express.json());")
    for resource in groups:
        lines.append(f"app.use('{api.base_path}/{resource}', {resource}Router);")
    lines.append("")
    lines.append("module.exports = app;")

    return "\n".join(lines)


def generate_env_template(intent: IntentSchema) -> str:
    lines = [
        "# Generated by Solum AI",
        "DATABASE_URL=postgresql://user:password@localhost:5432/mydb",
        "JWT_SECRET=change_this_to_a_random_secret",
        "PORT=3001",
    ]
    if intent.has_payments:
        lines.append("STRIPE_SECRET_KEY=sk_test_...")
        lines.append("STRIPE_WEBHOOK_SECRET=whsec_...")
    return "\n".join(lines)


def generate_setup_instructions(app_name: str, intent: IntentSchema) -> list[str]:
    steps = [
        f"# {app_name} — Setup Instructions (generated by Solum AI)",
        "1. Copy .env.example to .env and fill in your values",
        "2. Run: npm install express zod jsonwebtoken @prisma/client",
        "3. Run: npx prisma db push  (applies the generated schema)",
        "4. Run: npx prisma generate (generates the Prisma client)",
        "5. Start your server: node server.js",
        "6. The API is available at http://localhost:3001/api/v1",
    ]
    if intent.has_payments:
        steps.append("7. Configure Stripe keys for payment endpoints")
    return steps


def build_runtime_artifacts(
    db: DBSchema,
    api: APISchema,
    auth: AuthSchema,
    intent: IntentSchema,
) -> RuntimeArtifacts:
    return RuntimeArtifacts(
        prisma_schema=generate_prisma(db, intent.app_name),
        express_routes=generate_express_routes(api, auth, intent.app_name),
        env_template=generate_env_template(intent),
        setup_instructions=generate_setup_instructions(intent.app_name, intent),
    )